CREATE TABLE catalog_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), key text NOT NULL UNIQUE, kind text NOT NULL CHECK (kind IN ('product', 'service', 'part', 'labor', 'fee')), deactivated_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE catalog_item_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), catalog_item_id uuid NOT NULL REFERENCES catalog_items(id), version_number integer NOT NULL CHECK (version_number > 0), name text NOT NULL, description text, currency char(3) NOT NULL, unit_amount_minor bigint NOT NULL CHECK (unit_amount_minor >= 0), effective_from timestamptz NOT NULL DEFAULT now(), effective_to timestamptz, created_at timestamptz NOT NULL DEFAULT now(), CHECK (effective_to IS NULL OR effective_to > effective_from), UNIQUE(catalog_item_id, version_number));
CREATE TABLE quotes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), customer_profile_id uuid REFERENCES customer_profiles(id), created_by_user_id uuid NOT NULL REFERENCES users(id), status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'issued', 'expired', 'cancelled')), currency char(3) NOT NULL, pricing_context jsonb NOT NULL, total_amount_minor bigint NOT NULL CHECK (total_amount_minor >= 0), idempotency_key uuid NOT NULL, expires_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(created_by_user_id, idempotency_key));
CREATE TABLE quote_line_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), quote_id uuid NOT NULL REFERENCES quotes(id), catalog_item_id uuid NOT NULL REFERENCES catalog_items(id), catalog_item_version_id uuid NOT NULL REFERENCES catalog_item_versions(id), item_key text NOT NULL, name text NOT NULL, quantity integer NOT NULL CHECK (quantity > 0), currency char(3) NOT NULL, unit_amount_minor bigint NOT NULL CHECK (unit_amount_minor >= 0), line_amount_minor bigint NOT NULL CHECK (line_amount_minor >= 0), created_at timestamptz NOT NULL DEFAULT now(), CHECK (line_amount_minor = unit_amount_minor * quantity));
CREATE INDEX catalog_item_versions_active_idx ON catalog_item_versions (catalog_item_id, effective_from DESC) WHERE effective_to IS NULL;
CREATE INDEX quote_line_items_quote_id_idx ON quote_line_items (quote_id);
CREATE FUNCTION reject_catalog_quote_history_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Catalog versions and quote line items are immutable.'; END; $$;
CREATE TRIGGER catalog_item_versions_immutable BEFORE UPDATE OR DELETE ON catalog_item_versions FOR EACH ROW EXECUTE FUNCTION reject_catalog_quote_history_mutation();
CREATE TRIGGER quote_line_items_immutable BEFORE UPDATE OR DELETE ON quote_line_items FOR EACH ROW EXECUTE FUNCTION reject_catalog_quote_history_mutation();
